{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Monitor Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Memory usage per application",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10, memory_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Current total Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_Cached_bytes-node_memory_Buffers_bytes"
    }
   ]
  },
  {
   "title": "Current total free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  { "title": "Monitor CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU usage per application",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10, cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "CPU utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Free CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100  ",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Monitor Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Available partitions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device!~\"tmpfs\", mountpoint!~\"/etc/hostname|/etc/resolv.conf|/etc/hosts\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk read rate per application",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10,disk_read)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Disk read rate per application",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10,disk_read)", "legendFormat": "{{process}}" }
   ]
  }
 ]
}