global:
  # default scrape_interval
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "pushgateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["pushgateway:9091"]
